### PR TITLE
Support add `import.meta.env.__${APPNAME}_VERSION__` in the App

### PR DESCRIPTION
**Pull request by censujiang**
I have tested it rigorously and currently this function works fine

### CODE REVIEW

**Comment by ZhongxuYang** [comment]
Hi, thanks for your PR!

But referencing information like `import.meta.env.__${APPNAME}_VERSION__` will complicate usage given the premise that global variables are already provided. This may cause confusion for users.

You can also describe a more specific usage scenario about the need to support this approach.

Thanks again for your PR!

**Comment by censujiang** [comment]
In your use, when the method is mounted on the window object, the version number cannot be obtained in SSR mode. In the new method I added, I mounted it to import.meta.env for standard use, which not only facilitates the application itself to call the version number in any case, but also facilitates other plugins to call this

**Comment by censujiang** [comment]
I hope you will consider this pull request as soon as possible, thank you!

**Comment by censujiang** [comment]
Hello? This pull request need to deel with.

**Comment by ZhongxuYang** [comment]
Sorry for not paying attention to the content on Github on weekdays.

This function has been added similarly in [v0.0.9](https://github.com/ZhongxuYang/vite-plugin-version-mark/tree/v0.0.9
) (avoiding the introduction of the new `ifImportMeta` config, but modifying the mixin method of `ifGlobal`), and the version information can now be read in the node.js environment.

**Comment by censujiang** [comment]
Ok, I saw your update log, by the way my ID is @censujiang not @censujian

**Pull request closed without merging**
